# Generated by Django 4.1.2 on 2022-10-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('f_crear', models.DateTimeField(auto_now_add=True)),
                ('tipouser_1', models.CharField(max_length=30)),
                ('tipouser_2', models.CharField(max_length=30)),
                ('tipouser_3', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
