# Generated by Django 4.1.2 on 2022-10-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='tipouser_1',
            new_name='tipouser',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='tipouser_2',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='tipouser_3',
        ),
    ]
