# Generated by Django 4.1.2 on 2022-11-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_agenda_alter_usuarios_f_crear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='chassis',
            new_name='chasis',
        ),
    ]
